baseURL = "https://owncloud.github.io/ocis-hello/"
languageCode = "en-us"
title = "ownCloud Infinite Scale: Hello"
pygmentsUseClasses = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "ownCloud GmbH"
  description = "Example service for Reva/oCIS"
  keywords = "reva, ocis"
